name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}   # e.g. acrweek07s224911605.azurecr.io
  ACR_NAME: ${{ secrets.ACR_NAME }}                   # e.g. acrweek07s224911605
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # IMPORTANT: az acr login expects SHORT NAME, not login server
      - name: Login to Azure Container Registry
        run: az acr login --name $ACR_NAME

      - name: Build and Push Frontend Image
        run: |
          docker build -t $ACR_LOGIN_SERVER/frontend:latest ./frontend/
          docker push $ACR_LOGIN_SERVER/frontend:latest
